CREATE TABLE categories(
                           id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           category_name VARCHAR ,
                           chat_id BIGINT   NOT NULL


);